### PR TITLE
Fix `aggregate-approx` option

### LINKED ISSUE #430: Bug with -aa
If you feed it a file with a large number of IP addresses with -aa. The previous released version will give you great feedback. With the latest version it will default to `0.0.0.0/0`. 
```
# cat /tmp/test.txt |mapcidr -aa

                   ____________  ___
  __ _  ___ ____  / ___/  _/ _ \/ _ \
 /  ' \/ _ '/ _ \/ /___/ // // / , _/
/_/_/_/\_,_/ .__/\___/___/____/_/|_|
          /_/

                projectdiscovery.io

[INF] Current mapcidr version v1.1.34 (latest)
0.0.0.0/0

----------------------------------------------------------------

# cat /tmp/test.txt |./mapcidr -aa

                   ____________  ___
  __ _  ___ ____  / ___/  _/ _ \/ _ \
 /  ' \/ _ '/ _ \/ /___/ // // / , _/
/_/_/_/\_,_/ .__/\___/___/____/_/|_|
          /_/

                projectdiscovery.io

[INF] Current mapcidr version v1.1.16 (outdated)
10.1.6.0/20
```
Im not sure where the break is between 1.1.34 and 1.1.16 is.

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
- closes #430

### CODE REVIEW

File: ip.go [hunk 1]
```diff
@@ -533,27 +533,38 @@ func AggregateApproxIPs(ips []*net.IPNet) ([]*net.IPNet, error) {
...
-			if ip1[i]&mask == ip2[i]&mask {
-				commonPrefixLen += 1
-				mask >>= 1
-			} else {
-				break
+	cidrs := make(map[string]*net.IPNet)
+	for _, ip := range ips {
+		if n, ok := cidrs[ip.IP.Mask(net.CIDRMask(24, 32)).String()]; ok {
+			var baseNet byte
+			var nowN, newN byte
```
Comment (dogancanbakir) [inline ip.go:540]: names can be more descriptive

File: ip.go [hunk 2]
```diff
@@ -533,27 +533,38 @@ func AggregateApproxIPs(ips []*net.IPNet) ([]*net.IPNet, error) {
...
+			for i := 8; i > 0; i-- {
+				nowN = n.IP[3] & (1 << (i - 1)) >> (i - 1)
```
Comment (dogancanbakir) [inline ip.go:542]: can be a small function with a descriptive name

**Review by dogancanbakir — APPROVED** [review]

**Review by Mzack9999 — APPROVED** [review]
